### ISSUE TITLE
Panic on GIR codegen

### ISSUE THREAD

**Issue by SolarLiner** [gtk-rs/gir#1036]
I'm trying to generate a sys crate for `upower-glib` and the tool panics:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/codegen/sys/cargo_toml.rs:117:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: libgir::codegen::sys::cargo_toml::generate
   4: libgir::codegen::sys::generate
   5: gir::main
```

I have attached the related GIR file, to which I have applied the `fix.sh` script, without effect on the panic.

**Comment by bilelmoussaoui** [comment]
Can you paste the Gir.toml configuration as well?

**Comment by SolarLiner** [comment]
```toml
[options]
work_mode = "sys"
library = "UPowerGlib"
version = "1.0"
target_path = "./upower-sys"
girs_dir = "./gir-files"

external_libraries = [
    "GObject",
    "Glib",
]
```
