### ISSUE TITLE
Allow to define custom doc aliases

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1067]
I have this use case in gtk4-rs
```toml
    [[object.function]]
    name = "activate_action_variant"
    rename = "activate_action"
    [[object.function]]
    name = "activate_action"
    ignore = true # we use activate_action_variant instead
```

The generated code looks like
```rust
    #[doc(alias = "gtk_widget_activate_action_variant")]
    fn activate_action(&self, name: &str, args: Option<&glib::Variant>) -> bool;
```

What I would like to be able to achieve is producing this code 
```rust
    #[doc(alias = "gtk_widget_activate_action_variant")]
    #[doc(alias = "gtk_widget_activate_action")]
    fn activate_action(&self, name: &str, args: Option<&glib::Variant>) -> bool;
```

Maybe having a `doc_alias = []` option would make sense? 
```toml
    [[object.function]]
    name = "activate_action_variant"
    rename = "activate_action"
    doc_alias = ["gtk_widget_activate_action"]
```
