### ISSUE TITLE
cfg_condition doesn't affect flags

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1081]
Doing so in gtk4-rs
```toml
[[object]]
name = "Gtk.PrintCapabilities"
status = "generate"
cfg_condition = "target_os = \"linux\""
```
Where PrintCapabilities is a flag, it doesn't generate any cfg attribute at all.
