### ISSUE TITLE
Potential naming clash of vX_Y features between libraries

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gir#1099]
While updating libhandy-rs I realized for the first time, that gir generated code contains version numbers that are a mix of all involved dependencies.

Currently, this is not problem because the version numbers of libhandy, glib and gtk are neatly separated. But I was wondering if this is really future proof. Maybe having version names like `gtk_v3_24` could prove helpful at some point. (It will add some extra noise to gtk's Cargo.toml though.)

Example from libhandy-rs

```rust
pub struct ApplicationWindowBuilder {
    show_menubar: Option<bool>,
    #[cfg(any(feature = "v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v2_4")))]
    accept_focus: Option<bool>,
    //application: /*Unknown type*/,
    #[cfg(any(feature = "v3_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v3_4")))]
    attached_to: Option<gtk::Widget>,
    #[cfg(any(feature = "v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v2_4")))]
    decorated: Option<bool>,
    default_height: Option<i32>,
    default_width: Option<i32>,
```

Activate all gtk3 versions in libhandy-rs

```toml
[features]
default = [ "v1_0" ]
v1_0 = [ "v3_24", "ffi/v1_0" ]
v1_2 = [ "v1_0", "ffi/v1_2" ]
dox = []

# GTK versions
v3_0 = []
v3_2 = [ "v3_0" ]
v3_4 = [ "v3_2" ]
v3_6 = [ "v3_4" ]
v3_8 = [ "v3_6" ]
v3_10 = [ "v3_8" ]
v3_12 = [ "v3_10" ]
v3_14 = [ "v3_12" ]
v3_16 = [ "v3_14" ]
v3_18 = [ "v3_16" ]
v3_20 = [ "v3_18" ]
v3_22 = [ "v3_20" ]
v3_24 = [ "v3_22" ]
```
