### ISSUE TITLE
Add support to update callback parameters

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#1209]
For now, only signal callback parameters can be update through the `Gir.toml` file. It'd be nice to extend it to function with callbacks.

Something like:

```toml
    [[object.function]]
    name = "function_name"
        [[object.function.parameter]]
        name = "parameter_name"
             [[object.function.parameter.parameter]]
             name = "callback_parameter_name"
             nullable = false # just for the example
```
