### ISSUE TITLE
Allow targeting self parameter in a function configuration

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gir#1246]
Currently, I have this function that's generated automatically

```rust

    #[doc(alias = "gdk_file_list_get_files")]
    #[doc(alias = "get_files")]
    pub fn files(&mut self) -> Vec<gio::File> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::gdk_file_list_get_files(
                self.to_glib_none_mut().0,
            ))
        }
    }
```

Of course, that's completely wrong because self shouldn't be `&mut` here. So I want to override it by setting `const = true` for the self parameter, except that doesn't work with

```toml
    [[object.function]]
    name = "get_files"
        [[object.function.parameter]]
        name = "self"
        const = true
```

but it does work with `pattern = "*"`
