### ISSUE TITLE
Invalid GIR File Format in AstalApps-0.1.gir Causes Parsing Error

### ISSUE THREAD

**Issue by this-cat** [gtk-rs/gir#1651]
``` toml
[options]
work_mode = "normal"
library = "AstalApps"
version = "0.1"
girs_directories = ["/usr/share/gir-1.0"]
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

```

When using the AstalApps-0.1.gir file with Rust's GIR tool (gtk-rs/gir), an error occurs due to an invalid format in the <constant> element. The error message is:

``` txt
Error: "GirXml: /usr/share/gir-1.0/AstalApps-0.1.gir at line 615:2: Attribute `type` on element <constant> is required."
```

The problematic section in /usr/share/gir-1.0/AstalApps-0.1.gir is:
```xml
<constant name="MAJOR_VERSION" c:identifier="ASTAL_APPS_MAJOR_VERSION" value="0">
    <type name="gint" c:type="gint" />
</constant>
```
