### ISSUE TITLE
Gir should sometimes generate Option<Type> instead of Type

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gir#278]
Hello.
For this [signal](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-create), the return type generated by the binding should be `Option<Widget>` instead of only `Widget` because the return value can be null:
"a newly allocated WebKitWebView widget or NULL to propagate the event further."
[Here is the currently generated binding.](https://github.com/antoyo/webkit2gtk-rs/blob/master/src/auto/web_view.rs#L458)
Thanks to fix this issue.

**Comment by EPashkin** [comment]
Try use config https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L467-L468
If it no effect we try to add usage of `nullable` for signals.

**Comment by antoyo** [comment]
It does not seem to work for signals.
I tried the following:
```toml
[[object]]
name = "WebKit2.WebView"
status = "generate"
    [[object.signal]]
    name = "create"
    version = "2.6"
        [object.signal.return]
        nullable = true
```
Is it the right syntax?
