### ISSUE TITLE
Support for functions that return GPtrArray

### ISSUE THREAD

**Issue by msehnout** [gtk-rs/gir#594]
I would like to generate bindings to Network Manager. My first use case is to get active connections. It is implemented in this function:
```C
const GPtrArray *nm_client_get_active_connections (NMClient *client);
```
which can be found here: https://github.com/NetworkManager/NetworkManager/blob/master/libnm/nm-client.h#L315
Using this configuration for the gir generator:
```toml
[options]
work_mode = "sys"
library = "NM"
version = "1.0"
min_cfg_version = "1.0"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

generate = [
   "NM.ActiveConnection",
   "NM.Client",
]
```
I was able to generate this function:
```rust
//fn get_active_connections(&self) -> /*Unknown conversion*//*Unimplemented*/PtrArray TypeId { ns_id: 1, id: 9 };
```
It would be really nice, if gir could generate these functions automatically :-). I guess it would be useful with any function that returns an array.
