### ISSUE TITLE
Allow to skip the build.rs when building the doc

### ISSUE THREAD

**Issue by Boiethios** [gtk-rs/gir#818]
A published sys crate cannot have its doc on [docs.rs](docs.rs) (unless the linked library is installed in the machine that does the build) because the build script returns an error while searching for the library, and thus the doc build breaks.

There should be a feature "docs.rs", so that the build.rs could be:

```rust
#[cfg(feature = "docs-rs")]
fn main() {} // Skip the script when the doc is building

#[cfg(not(feature = "docs-rs"))]
fn main() {
    // The generated code for the build
}
```

And in the Cargo.toml:

```toml
[features]
docs-rs = []

[package.metadata.docs.rs]
features = [ "docs.rs" ]
```

I've made a POC, and it works well: https://docs.rs/goa-sys
